# Generated by Django 4.1.3 on 2022-11-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_descrption'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experiance',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='job',
            name='published_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='vanacy',
            field=models.IntegerField(default=1),
        ),
    ]
